[workspace.package]
name = "zkp-learning"
version = "0.1.0"
edition = "2021"
authors = ["luckychacha"]

[workspace]
members = [
	"simple-example",
	"fibonacci"
]

[workspace.dependencies]
halo2_proofs = "0.3.0"