[package]
name = "simple-example"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Lesson 1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff.workspace = true
halo2_proofs.workspace = true
